var addPowerUp = function(id, cost, label, description, section, func, onetime, sell) {
	powerups[id] = 0;
	powerupsfuncs[id] = {
		"cost": cost,
		"label": label,
		"section": section,
		"description": description,
		"func": func,
		"onetime": onetime,
		"sell": sell || null
	};
}

var listPowerUp = function(id) {
	if($("#" + id).length === 0) {
		var func = powerupsfuncs[id];
		var target = $("#" + func["section"]);
		var li = $("<li>");
		li.attr("id", id);
		li.html(func["label"]);
		target.append(li);
		var q = $("<q>");
		var html = "";
		html += (func["cost"].effort !== 0 ? "Effort: " + numberWithCommas(compInt(func["cost"].effort, powerups[id]).toFixed(0)) : "") + " ";
		html += (func["cost"].paperwork !== 0 ? "Paperwork: " + numberWithCommas(compInt(func["cost"].paperwork, powerups[id]).toFixed(0)) : "") + " ";
		html += (func["cost"].yessir !== 0 ? "Yes Sir: " + numberWithCommas(compInt(2, powerups[id]).toFixed(0)) : "") + " ";
		html += (func["cost"].bribery !== 0 ? "Bribery: " + numberWithCommas(compInt(func["cost"].bribery, powerups[id]).toFixed(0)) : "");
		q.html(html);
		q.attr("id", id + "_q");
		li.append(q);
		var pre = $("<pre>");
		pre.attr("id", id + "_pre");
		pre.html("" + powerups[id]);
		li.append(pre);
		/*
		You know what? As of 11/14/13, 9:54PM:
		
		I don't like selling.
		
		Seems to be a moot point, if you ask me. And if you're asking me while reading comments, then STOP PROJECTING YOUR THOUGHTS INTO MY HEAD
		
		var sell = $("<a href=\"javascript:void(0)\">Sell</a>");
		sell.attr("myPow", id);
		sell.css({"position": "absolute", "top": "3px", "right": "3px"});
		li.append(sell);
		sell.click(function(e) {
			e.stopPropagation();
			var id = $(this).attr("myPow");
			if(powerups[id] > 0) {
				powerups[id]--;
				var effortVal = compInt(func["cost"].effort, powerups[id]), paperworkVal = compInt(func["cost"].paperwork, powerups[id]), yessirVal = compInt(func["cost"].yessir, powerups[id]);
				efforttally += (effortVal * 0.5);
				paperworktally += (paperworkVal * 0.5);
				yessirtally  += (yessirVal * 0.5);
				var q = $("#" + id + "_q");
				var html = "";
				html += (func["cost"].effort !== 0 ? "Effort: " + numberWithCommas(compInt(func["cost"].effort, powerups[id]).toFixed(0)) : "") + " ";
				html += (func["cost"].paperwork !== 0 ? "Paperwork: " + numberWithCommas(compInt(func["cost"].paperwork, powerups[id]).toFixed(0)) : "") + " ";
				html += (func["cost"].yessir !== 0 ? "Yes Sir: " + numberWithCommas(compInt(func["cost"].yessir, powerups[id]).toFixed(0)) : "");
				
				q.html(html);
				var pre = $("#" + id + "_pre");
				pre.html("Total: " + powerups[id]);
				if(func["sell"] !== null) func["sell"]();
			}
		});*/
		li.click(function(goal, id) {
			return function() {
				var effortVal = compInt(func["cost"].effort, powerups[id]),
					paperworkVal = compInt(func["cost"].paperwork, powerups[id]),
					yessirVal = compInt(func["cost"].yessir, powerups[id]),
					briberyVal = compInt(func["cost"].bribery, powerups[id]);
				if(efforttally >= effortVal &&
					paperworktally >= paperworkVal &&
					yessirtally >= yessirVal &&
					briberytally >= briberyVal) {
						if(func["onetime"] === true && powerups[id] > 0) return;
						powerups[id]++;
						efforttally -= effortVal;
						paperworktally -= paperworkVal;
						yessirtally -= yessirVal;
						briberytally -= briberyVal;
						var q = $("#" + id + "_q");
						var html = "";
						html += (func["cost"].effort !== 0 ? "Effort: " + numberWithCommas(compInt(func["cost"].effort, powerups[id]).toFixed(0)) : "") + " ";
						html += (func["cost"].paperwork !== 0 ? "Paperwork: " + numberWithCommas(compInt(func["cost"].paperwork, powerups[id]).toFixed(0)) : "") + " ";
						html += (func["cost"].yessir !== 0 ? "Yes Sir: " + numberWithCommas(compInt(func["cost"].yessir, powerups[id]).toFixed(0)) : "");
						html += (func["cost"].bribery !== 0 ? "Bribery: " + numberWithCommas(compInt(func["cost"].bribery, powerups[id]).toFixed(0)) : "");
						q.html(html);
						var pre = $("#" + id + "_pre");
						pre.html("" + powerups[id]);
						recalculate();
				}
			}
		}(func, id));
		var label = $("<span>");
		label.html(func["description"]());
		label.css({"position": "absolute", "right": "3px", "top": "3px", "font-size": "10px"});
		li.append(label);
		//li.tooltip({track: true});
	}
}
/*
	temporary function. Will not be permanent once game is in beta.
*/
var buildPows = function() {
	var targs = ["#effortPrimary","#effortSecondary","#effortTertiary",
		"#paperworkPrimary","#paperworkSecondary","#paperworkTertiary",
		"#yessirPrimary","#yessirSecondary","#yessirTertiary",
		"#briberyPrimary","#briberySecondary","#briberyTertiary"].join(",");
	$(targs).empty();
	listPowerUp("grindstone");	listPowerUp("back");	listPowerUp("pain");	listPowerUp("mile");	listPowerUp("believe");
	listPowerUp("advpaper");	listPowerUp("ultpaper");	listPowerUp("sweetpaper");	listPowerUp("multidimenpaper");	listPowerUp("prettyprettypen");
	listPowerUp("stronghandshakes");	listPowerUp("deeperlies");	listPowerUp("longcommercials");	listPowerUp("infiltratereddit");	listPowerUp("telepathy");
	listPowerUp("fivebribe");	listPowerUp("seventyfivebribe");	listPowerUp("fivehundredbribe");	listPowerUp("twentyfivehundredbribe");	listPowerUp("thirtythousandbribe");
	listPowerUp("stranger");	listPowerUp("perfectstrangers");	listPowerUp("perfectstrangers2");		
	listPowerUp("acquaintance");	listPowerUp("gettingtoknowyou");	listPowerUp("gettingtoknowallaboutyou");		
	listPowerUp("friend");	listPowerUp("joey");	listPowerUp("chandler");		
	listPowerUp("bro");	listPowerUp("budlight");	listPowerUp("collar");		
	listPowerUp("bestfriend");	listPowerUp("pizza");	listPowerUp("hideabody");		
	listPowerUp("bff");	listPowerUp("idkmbffj");	listPowerUp("instantgram");		
	listPowerUp("personallawyer");	listPowerUp("objection");	listPowerUp("takethat");		
	listPowerUp("sigother");	listPowerUp("cohabitate");	listPowerUp("cosign");		
	listPowerUp("superpac");	listPowerUp("babypac");	listPowerUp("mspac");		
	listPowerUp("staples");	listPowerUp("paperclips");	listPowerUp("paperbinders");		
	listPowerUp("pencil");	listPowerUp("sharpenedPencil");	listPowerUp("mechanicalpencil");		
	listPowerUp("pen");	listPowerUp("moreink");	listPowerUp("cyberpen");		
	listPowerUp("typewriter");	listPowerUp("wordprocessor");	listPowerUp("talktotext");		
	listPowerUp("printer");	listPowerUp("laserprinter");	listPowerUp("threeinone");		
	listPowerUp("altavista");	listPowerUp("lycos");	listPowerUp("compuserve");		
	listPowerUp("orphans");	listPowerUp("gruel");	listPowerUp("posters");		
	listPowerUp("robots");	listPowerUp("laserguns");	listPowerUp("sentience");		
	listPowerUp("unicron");	listPowerUp("matrix");	listPowerUp("disc");		
	listPowerUp("tippiecanoe");	listPowerUp("tyler");	listPowerUp("harrison");		
	listPowerUp("harry");	listPowerUp("barkley");	listPowerUp("truman");		
	listPowerUp("ike");	listPowerUp("nixon");	listPowerUp("eisenhower");		
	listPowerUp("great");	listPowerUp("johnson");	listPowerUp("kennedy");		
	listPowerUp("taxes");	listPowerUp("quayle");	listPowerUp("bush");		
	listPowerUp("timeforchange");	listPowerUp("gore");	listPowerUp("clinton");		
	listPowerUp("change");	listPowerUp("biden");	listPowerUp("obama");		
	listPowerUp("handsacrossamerica");	listPowerUp("morelube");	listPowerUp("chickenmeanscock");		
	listPowerUp("morelies");	listPowerUp("jobs");	listPowerUp("hungryhungry");		
	listPowerUp("handmoney");	listPowerUp("smallermoney");	listPowerUp("biggerhands");		
	listPowerUp("envelopemoney");	listPowerUp("wowenvelope");	listPowerUp("digitalenvelope");		
	listPowerUp("handbagmoney");	listPowerUp("conch");	listPowerUp("pradu");		
	listPowerUp("palletmoney");	listPowerUp("inceptionpallet");	listPowerUp("forklifts");		
	listPowerUp("buildingmoney");	listPowerUp("twobuildings");	listPowerUp("twomansions");		
	listPowerUp("citymoney");	listPowerUp("community");	listPowerUp("subway");		
	listPowerUp("nationmoney");	listPowerUp("unofmoney");	listPowerUp("continents");		
	listPowerUp("planetmoney");	listPowerUp("moon");	listPowerUp("uranus");		
	listPowerUp("solarmoney");	listPowerUp("diamond");	listPowerUp("toomuchmoney");		
	/*listPowerUp("grindstone");	listPowerUp("back");	listPowerUp("pain");	listPowerUp("mile");	listPowerUp("believe");
	listPowerUp("stranger");	listPowerUp("perfectstrangers");	listPowerUp("perfectstrangers2");		
	listPowerUp("acquaintance");	listPowerUp("gettingtoknowyou");	listPowerUp("gettingtoknowallaboutyou");		
	listPowerUp("friend");	listPowerUp("joey");	listPowerUp("chandler");		
	listPowerUp("bro");	listPowerUp("budlight");	listPowerUp("collar");		
	listPowerUp("bestfriend");	listPowerUp("pizza");	listPowerUp("hideabody");		
	listPowerUp("bff");	listPowerUp("idkmbffj");	listPowerUp("instantgram");		
	listPowerUp("personallawyer");	listPowerUp("objection");	listPowerUp("takethat");		
	listPowerUp("sigother");	listPowerUp("cohabitate");	listPowerUp("cosign");		
	listPowerUp("superpac");	listPowerUp("babypac");	listPowerUp("mspac");		
	listPowerUp("staples");	listPowerUp("paperclips");	listPowerUp("paperbinders");		
	listPowerUp("pencil");	listPowerUp("sharpenedPencil");	listPowerUp("mechanicalpencil");		
	listPowerUp("pen");	listPowerUp("moreink");	listPowerUp("cyberpen");		
	listPowerUp("typewriter");	listPowerUp("wordprocessor");	listPowerUp("talktotext");		
	listPowerUp("printer");	listPowerUp("laserprinter");	listPowerUp("threeinone");		
	listPowerUp("altavista");	listPowerUp("lycos");	listPowerUp("compuserve");		
	listPowerUp("orphans");	listPowerUp("gruel");	listPowerUp("posters");		
	listPowerUp("robots");	listPowerUp("laserguns");	listPowerUp("sentience");		
	listPowerUp("unicron");	listPowerUp("matrix");	listPowerUp("disc");		
	listPowerUp("tippiecanoe");	listPowerUp("tyler");	listPowerUp("harrison");		
	listPowerUp("harry");	listPowerUp("barkley");	listPowerUp("truman");		
	listPowerUp("ike");	listPowerUp("nixon");	listPowerUp("eisenhower");		
	listPowerUp("great");	listPowerUp("johnson");	listPowerUp("kennedy");		
	listPowerUp("taxes");	listPowerUp("quayle");	listPowerUp("bush");		
	listPowerUp("timeforchange");	listPowerUp("gore");	listPowerUp("clinton");		
	listPowerUp("change");	listPowerUp("biden");	listPowerUp("obama");		
	listPowerUp("handsacrossamerica");	listPowerUp("morelube");	listPowerUp("chickenmeanscock");		
	listPowerUp("morelies");	listPowerUp("jobs");	listPowerUp("hungryhungry");		*/
}

var addThePowerUps = function() {
	addPowerUp("stranger", {effort: 15, paperwork: 0, yessir: 0, bribery: 0}, "Stranger", function() { return "+" + (0.1 + flags.flag("perfectstrangers") + flags.flag("perfectstrangers2")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (0.1 + flags.flag("perfectstrangers") + flags.flag("perfectstrangers2")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("acquaintance", {effort: 100, paperwork: 0, yessir: 0, bribery: 0}, "Acquaintance", function() { return "+" + (0.5 + flags.flag("gettingtoknowyou") + flags.flag("gettingtoknowallaboutyou")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (0.5 + flags.flag("gettingtoknowyou") + flags.flag("gettingtoknowallaboutyou")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("friend", {effort: 900, paperwork: 0, yessir: 0, bribery: 0}, "Friend", function() { return "+" + (3 + flags.flag("joey") + flags.flag("chandler")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (3 + flags.flag("joey") + flags.flag("chandler")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("bro", {effort: 25437, paperwork: 0, yessir: 0, bribery: 0}, "Bro", function() { return "+" + (50 + flags.flag("budlight") + flags.flag("collar")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (50 + flags.flag("budlight") + flags.flag("collar")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("bestfriend", {effort: 150000, paperwork: 5000, yessir: 0, bribery: 0}, "Best Friend", function() { return "+" + (300 + flags.flag("pizza") + flags.flag("hideabody")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (300 + flags.flag("pizza") + flags.flag("hideabody")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("bff", {effort: 314159, paperwork: 133700, yessir: 0, bribery: 0}, "BFF", function() { return "+" + (2400 + flags.flag("idkmbffj") + flags.flag("instantgram")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (2400 + flags.flag("idkmbffj") + flags.flag("instantgram")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("personallawyer", {effort: 1000000, paperwork: 675000, yessir: 10000, bribery: 0}, "Personal Lawyer", function() { return "+" + (9999 + flags.flag("objection") + flags.flag("takethat")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (9999 + flags.flag("objection") + flags.flag("takethat")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("sigother", {effort: 11235813, paperwork: 3333360, yessir: 270000, bribery: 0}, "Significant Other", function() { return "+" + (70000 + flags.flag("cohabitate") + flags.flag("cosign")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (70000 + flags.flag("cohabitate") + flags.flag("cosign")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("superpac", {effort: 81000000, paperwork: 7598950, yessir: 999000, bribery: 0}, "Super PAC", function() { return "+" + (500000 + flags.flag("babypac") + flags.flag("mspac")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (500000 + flags.flag("babypac") + flags.flag("mspac")) * num,"paperwork": 0,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("staples", {effort: 0, paperwork: 15, yessir: 0, bribery: 0}, "Staples", function() { return "+" + (0.1 + flags.flag("paperclips") + flags.flag("paperbinders")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (0.1 + flags.flag("paperclips") + flags.flag("paperbinders")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("pencil", {effort: 0, paperwork: 100, yessir: 0, bribery: 0}, "Pencil", function() { return "+" + (0.5 + flags.flag("sharpenedPencil") + flags.flag("mechanicalpencil")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (0.5 + flags.flag("sharpenedPencil") + flags.flag("mechanicalpencil")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("pen", {effort: 0, paperwork: 900, yessir: 0, bribery: 0}, "Pen", function() { return "+" + (3 + flags.flag("moreink") + flags.flag("cyberpen")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (3 + flags.flag("moreink") + flags.flag("cyberpen")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("typewriter", {effort: 0, paperwork: 25437, yessir: 0, bribery: 0}, "Typewriter", function() { return "+" + (50 + flags.flag("wordprocessor") + flags.flag("talktotext")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (50 + flags.flag("wordprocessor") + flags.flag("talktotext")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("printer", {effort: 540000, paperwork: 150000, yessir: 0, bribery: 0}, "Printer", function() { return "+" + (300 + flags.flag("laserprinter") + flags.flag("threeinone")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (300 + flags.flag("laserprinter") + flags.flag("threeinone")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("altavista", {effort: 4850000, paperwork: 314159, yessir: 0, bribery: 0}, "Email Address", function() { return "+" + (2400 + flags.flag("lycos") + flags.flag("compuserve")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (2400 + flags.flag("lycos") + flags.flag("compuserve")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("orphans", {effort: 25600000, paperwork: 1000000, yessir: 80000, bribery: 0}, "Flock of orphans with your handwriting", function() { return "+" + (9999 + flags.flag("gruel") + flags.flag("posters")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (9999 + flags.flag("gruel") + flags.flag("posters")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("robots", {effort: 101200000, paperwork: 11235813, yessir: 670000, bribery: 0}, "Robots. God damned robots.", function() { return "+" + (70000 + flags.flag("laserguns") + flags.flag("sentience")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (70000 + flags.flag("laserguns") + flags.flag("sentience")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("unicron", {effort: 155848000, paperwork: 81000000, yessir: 1599000, bribery: 0}, "Living planet with amazing handwriting", function() { return "+" + (500000 + flags.flag("matrix") + flags.flag("disc")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (500000 + flags.flag("matrix") + flags.flag("disc")) * num,"yessir": 0,"bribery": 0};}, false);
	addPowerUp("tippiecanoe", {effort: 0, paperwork: 0, yessir: 15, bribery: 0}, "\"Tippecanoe and Tyler Too!\"", function() { return "+" + (0.1 + flags.flag("tyler") + flags.flag("harrison")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (0.1 + flags.flag("tyler") + flags.flag("harrison")) * num,"bribery": 0};}, false);
	addPowerUp("harry", {effort: 0, paperwork: 0, yessir: 100, bribery: 0}, "\"Give 'Em Hell, Harry!\"", function() { return "+" + (0.5 + flags.flag("barkley") + flags.flag("truman")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (0.5 + flags.flag("barkley") + flags.flag("truman")) * num,"bribery": 0};}, false);
	addPowerUp("ike", {effort: 0, paperwork: 0, yessir: 900, bribery: 0}, "\"I Like Ike!\"", function() { return "+" + (3 + flags.flag("nixon") + flags.flag("eisenhower")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (3 + flags.flag("nixon") + flags.flag("eisenhower")) * num,"bribery": 0};}, false);
	addPowerUp("great", {effort: 0, paperwork: 0, yessir: 25437, bribery: 0}, "\"A Time For Greatness\"", function() { return "+" + (50 + flags.flag("johnson") + flags.flag("kennedy")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (50 + flags.flag("johnson") + flags.flag("kennedy")) * num,"bribery": 0};}, false);
	addPowerUp("taxes", {effort: 9110000, paperwork: 647000, yessir: 150000, bribery: 0}, "\"No New Taxes\"", function() { return "+" + (300 + flags.flag("quayle") + flags.flag("bush")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (300 + flags.flag("quayle") + flags.flag("bush")) * num,"bribery": 0};}, false);
	addPowerUp("timeforchange", {effort: 44400000, paperwork: 1234567, yessir: 314159, bribery: 0}, "\"It's Time To Change America\"", function() { return "+" + (2400 + flags.flag("gore") + flags.flag("clinton")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (2400 + flags.flag("gore") + flags.flag("clinton")) * num,"bribery": 0};}, false);
	addPowerUp("change", {effort: 322222222, paperwork: 12345678, yessir: 1000000, bribery: 0}, "\"Change\"", function() { return "+" + (9999 + flags.flag("biden") + flags.flag("obama")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (9999 + flags.flag("biden") + flags.flag("obama")) * num,"bribery": 0};}, false);
	addPowerUp("handsacrossamerica", {effort: 5000000000, paperwork: 123456789, yessir: 11235813, bribery: 0}, "\"Free Sexual Favors For Everyone!\"", function() { return "+" + (70000 + flags.flag("morelube") + flags.flag("chickenmeanscock")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (70000 + flags.flag("morelube") + flags.flag("chickenmeanscock")) * num,"bribery": 0};}, false);
	addPowerUp("morelies", {effort: 8500000000, paperwork: 370370367, yessir: 134829756, bribery: 0}, "\"Here, Have Some Empty Promises\"", function() { return "+" + (500000 + flags.flag("jobs") + flags.flag("hungryhungry")) + " Yes Sir! Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (500000 + flags.flag("jobs") + flags.flag("hungryhungry")) * num,"bribery": 0};}, false);
	addPowerUp("handmoney", {effort: 745670965, paperwork: 37283548, yessir: 7456710, bribery: 15}, "Handful of Money", function() { return "+" + (0.1 + flags.flag("smallermoney") + flags.flag("biggerhands")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (0.1 + flags.flag("smallermoney") + flags.flag("biggerhands")) * num};}, false);
	addPowerUp("envelopemoney", {effort: 1394404705, paperwork: 69720235, yessir: 13944048, bribery: 100}, "Envelope of Money", function() { return "+" + (0.5 + flags.flag("wowenvelope") + flags.flag("digitalenvelope")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (0.5 + flags.flag("wowenvelope") + flags.flag("digitalenvelope")) * num};}, false);
	addPowerUp("handbagmoney", {effort: 2984026069, paperwork: 149201303, yessir: 29840263, bribery: 900}, "Handbag of Money", function() { return "+" + (3 + flags.flag("conch") + flags.flag("pradu")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (3 + flags.flag("conch") + flags.flag("pradu")) * num};}, false);
	addPowerUp("palletmoney", {effort: 7221343087, paperwork: 361067153, yessir: 72213436, bribery: 25437}, "Pallet of Money", function() { return "+" + (50 + flags.flag("inceptionpallet") + flags.flag("forklifts")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (50 + flags.flag("inceptionpallet") + flags.flag("forklifts")) * num};}, false);
	addPowerUp("buildingmoney", {effort: 19858693489, paperwork: 992934671, yessir: 198586949, bribery: 150000}, "Building of Money", function() { return "+" + (300 + flags.flag("twobuildings") + flags.flag("twomansions")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (300 + flags.flag("twobuildings") + flags.flag("twomansions")) * num};}, false);
	addPowerUp("citymoney", {effort: 28199344754, paperwork: 1409967233, yessir: 281993468, bribery: 314159}, "City of Money", function() { return "+" + (2400 + flags.flag("community") + flags.flag("subway")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (2400 + flags.flag("community") + flags.flag("subway")) * num};}, false);
	addPowerUp("nationmoney", {effort: 40043069551, paperwork: 2002153471, yessir: 400430725, bribery: 1000000}, "Nation of Money", function() { return "+" + (9999 + flags.flag("unofmoney") + flags.flag("continents")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (9999 + flags.flag("unofmoney") + flags.flag("continents")) * num};}, false);
	addPowerUp("planetmoney", {effort: 56861158762, paperwork: 2843057929, yessir: 568611630, bribery: 11235813}, "Planet of Money", function() { return "+" + (70000 + flags.flag("moon") + flags.flag("uranus")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (70000 + flags.flag("moon") + flags.flag("uranus")) * num};}, false);
	addPowerUp("solarmoney", {effort: 80742845442, paperwork: 4037142259, yessir: 807428515, bribery: 134829756}, "Solar System of Money", function() { return "+" + (500000 + flags.flag("diamond") + flags.flag("toomuchmoney")) + " Bribery Per Second";}, "briberyPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": 0,"bribery": (500000 + flags.flag("diamond") + flags.flag("toomuchmoney")) * num};}, false);
	addPowerUp("perfectstrangers", {effort: 500, paperwork: 0, yessir: 0, bribery: 0}, "Perfect Strangers", function() { return "+2 Effort For Every Stranger";}, "effortSecondary", function(num) { if( $("#perfectstrangers").length > 0 && num > 0) {$("#perfectstrangers").remove();}flags.flag("perfectstrangers", 2); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("perfectstrangers", 0);});
	addPowerUp("perfectstrangers2", {effort: 45000, paperwork: 0, yessir: 0, bribery: 0}, "Perfect Strangers Mk. II", function() { return "+50 Effort For Every Stranger";}, "effortSecondary", function(num) { if( $("#perfectstrangers2").length > 0 && num > 0) {$("#perfectstrangers2").remove();}flags.flag("perfectstrangers2", 50); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("perfectstrangers2", 0);});
	addPowerUp("gettingtoknowyou", {effort: 7600, paperwork: 0, yessir: 0, bribery: 0}, "Getting To Know You", function() { return "+5 Effort For Every Acquaintance";}, "effortSecondary", function(num) { if( $("#gettingtoknowyou").length > 0 && num > 0) {$("#gettingtoknowyou").remove();}flags.flag("gettingtoknowyou", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("gettingtoknowyou", 0);});
	addPowerUp("gettingtoknowallaboutyou", {effort: 98000, paperwork: 0, yessir: 0, bribery: 0}, "Getting To Know All About You", function() { return "+70 Effort For Every Acquaintance";}, "effortSecondary", function(num) { if( $("#gettingtoknowallaboutyou").length > 0 && num > 0) {$("#gettingtoknowallaboutyou").remove();}flags.flag("gettingtoknowallaboutyou", 70); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("gettingtoknowallaboutyou", 0);});
	addPowerUp("joey", {effort: 50000, paperwork: 0, yessir: 0, bribery: 0}, "Joey", function() { return "+10 Effort For Every Friend";}, "effortSecondary", function(num) { if( $("#joey").length > 0 && num > 0) {$("#joey").remove();}flags.flag("joey", 10); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("joey", 0);});
	addPowerUp("chandler", {effort: 222000, paperwork: 0, yessir: 0, bribery: 0}, "Chandler", function() { return "+115 Effort For Every Friend";}, "effortSecondary", function(num) { if( $("#chandler").length > 0 && num > 0) {$("#chandler").remove();}flags.flag("chandler", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("chandler", 0);});
	addPowerUp("budlight", {effort: 920000, paperwork: 0, yessir: 0, bribery: 0}, "Bud Light", function() { return "+115 Effort For Every Bro";}, "effortSecondary", function(num) { if( $("#budlight").length > 0 && num > 0) {$("#budlight").remove();}flags.flag("budlight", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("budlight", 0);});
	addPowerUp("collar", {effort: 3200000, paperwork: 0, yessir: 0, bribery: 0}, "Popped Collar", function() { return "+420 Effort For Every Bro";}, "effortSecondary", function(num) { if( $("#collar").length > 0 && num > 0) {$("#collar").remove();}flags.flag("collar", 420); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("collar", 0);});
	addPowerUp("pizza", {effort: 720000, paperwork: 42000, yessir: 0, bribery: 0}, "Pizza", function() { return "+500 Effort For Every Best Friend";}, "effortSecondary", function(num) { if( $("#pizza").length > 0 && num > 0) {$("#pizza").remove();}flags.flag("pizza", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("pizza", 0);});
	addPowerUp("hideabody", {effort: 3200000, paperwork: 118000, yessir: 0, bribery: 0}, "Hide A Body Maybe?", function() { return "+900 Effort For Every Best Friend";}, "effortSecondary", function(num) { if( $("#hideabody").length > 0 && num > 0) {$("#hideabody").remove();}flags.flag("hideabody", 900); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("hideabody", 0);});
	addPowerUp("idkmbffj", {effort: 1120000, paperwork: 77777, yessir: 0, bribery: 0}, "IDK, my BFF Jill?", function() { return "+1234 Effort For Every BFF";}, "effortSecondary", function(num) { if( $("#idkmbffj").length > 0 && num > 0) {$("#idkmbffj").remove();}flags.flag("idkmbffj", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("idkmbffj", 0);});
	addPowerUp("instantgram", {effort: 9876543, paperwork: 300000, yessir: 0, bribery: 0}, "Instant Gram (That's What The Kids Call It?)", function() { return "+5000 Effort For Every BFF";}, "effortSecondary", function(num) { if( $("#instantgram").length > 0 && num > 0) {$("#instantgram").remove();}flags.flag("instantgram", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("instantgram", 0);});
	addPowerUp("objection", {effort: 4810000, paperwork: 1475000, yessir: 49000, bribery: 0}, "OBJECTION!", function() { return "+25000 Effort For Every Personal Lawyer";}, "effortSecondary", function(num) { if( $("#objection").length > 0 && num > 0) {$("#objection").remove();}flags.flag("objection", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("objection", 0);});
	addPowerUp("takethat", {effort: 10240000, paperwork: 6675000, yessir: 260000, bribery: 0}, "TAKE THAT!!", function() { return "+50000 Effort For Every Personal Lawyer";}, "effortSecondary", function(num) { if( $("#takethat").length > 0 && num > 0) {$("#takethat").remove();}flags.flag("takethat", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("takethat", 0);});
	addPowerUp("cohabitate", {effort: 21345589, paperwork: 9999990, yessir: 679000, bribery: 0}, "Move In Together", function() { return "+150000 Effort For Every Significant Other";}, "effortSecondary", function(num) { if( $("#cohabitate").length > 0 && num > 0) {$("#cohabitate").remove();}flags.flag("cohabitate", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("cohabitate", 0);});
	addPowerUp("cosign", {effort: 144233377, paperwork: 50000000, yessir: 4110000, bribery: 0}, "Buy A House!", function() { return "+300000 Effort For Every Significant Other";}, "effortSecondary", function(num) { if( $("#cosign").length > 0 && num > 0) {$("#cosign").remove();}flags.flag("cosign", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("cosign", 0);});
	addPowerUp("babypac", {effort: 231777551, paperwork: 32000000, yessir: 1241100, bribery: 0}, "Baby PAC", function() { return "+1750000 Effort For Every Super PAC";}, "effortSecondary", function(num) { if( $("#babypac").length > 0 && num > 0) {$("#babypac").remove();}flags.flag("babypac", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("babypac", 0);});
	addPowerUp("mspac", {effort: 1557773120, paperwork: 68800000, yessir: 9000000, bribery: 0}, "Ms. PAC", function() { return "+5000000 Effort For Every Super PAC";}, "effortSecondary", function(num) { if( $("#mspac").length > 0 && num > 0) {$("#mspac").remove();}flags.flag("mspac", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("mspac", 0);});
	addPowerUp("paperclips", {effort: 0, paperwork: 500, yessir: 0, bribery: 0}, "Paperclips", function() { return "+2 Paperwork For Every Staples";}, "paperworkSecondary", function(num) { if( $("#paperclips").length > 0 && num > 0) {$("#paperclips").remove();}flags.flag("paperclips", 2); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("paperclips", 0);});
	addPowerUp("paperbinders", {effort: 0, paperwork: 45000, yessir: 0, bribery: 0}, "Paper Binders", function() { return "+50 Paperwork For Every Staples";}, "paperworkSecondary", function(num) { if( $("#paperbinders").length > 0 && num > 0) {$("#paperbinders").remove();}flags.flag("paperbinders", 50); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("paperbinders", 0);});
	addPowerUp("sharpenedPencil", {effort: 0, paperwork: 7600, yessir: 0, bribery: 0}, "Sharpened Pencil", function() { return "+5 Paperwork For Every Pencil";}, "paperworkSecondary", function(num) { if( $("#sharpenedPencil").length > 0 && num > 0) {$("#sharpenedPencil").remove();}flags.flag("sharpenedPencil", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("sharpenedPencil", 0);});
	addPowerUp("mechanicalpencil", {effort: 0, paperwork: 98000, yessir: 0, bribery: 0}, "Mechanical Pencil", function() { return "+70 Paperwork For Every Pencil";}, "paperworkSecondary", function(num) { if( $("#mechanicalpencil").length > 0 && num > 0) {$("#mechanicalpencil").remove();}flags.flag("mechanicalpencil", 70); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("mechanicalpencil", 0);});
	addPowerUp("moreink", {effort: 0, paperwork: 50000, yessir: 0, bribery: 0}, "MORE. INK.", function() { return "+10 Paperwork For Every Pen";}, "paperworkSecondary", function(num) { if( $("#moreink").length > 0 && num > 0) {$("#moreink").remove();}flags.flag("moreink", 10); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("moreink", 0);});
	addPowerUp("cyberpen", {effort: 0, paperwork: 222000, yessir: 0, bribery: 0}, "Cybernetic Pen", function() { return "+115 Paperwork For Every Pen";}, "paperworkSecondary", function(num) { if( $("#cyberpen").length > 0 && num > 0) {$("#cyberpen").remove();}flags.flag("cyberpen", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("cyberpen", 0);});
	addPowerUp("wordprocessor", {effort: 0, paperwork: 920000, yessir: 0, bribery: 0}, "Word Processor", function() { return "+115 Paperwork For Every Typewriter";}, "paperworkSecondary", function(num) { if( $("#wordprocessor").length > 0 && num > 0) {$("#wordprocessor").remove();}flags.flag("wordprocessor", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("wordprocessor", 0);});
	addPowerUp("talktotext", {effort: 0, paperwork: 3200000, yessir: 0, bribery: 0}, "Talk To Text", function() { return "+420 Paperwork For Every Typewriter";}, "paperworkSecondary", function(num) { if( $("#talktotext").length > 0 && num > 0) {$("#talktotext").remove();}flags.flag("talktotext", 420); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("talktotext", 0);});
	addPowerUp("laserprinter", {effort: 3110000, paperwork: 720000, yessir: 0, bribery: 0}, "Laser Printer", function() { return "+500 Paperwork For Every Printer";}, "paperworkSecondary", function(num) { if( $("#laserprinter").length > 0 && num > 0) {$("#laserprinter").remove();}flags.flag("laserprinter", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("laserprinter", 0);});
	addPowerUp("threeinone", {effort: 8240000, paperwork: 3200000, yessir: 0, bribery: 0}, "Three In One Printer", function() { return "+900 Paperwork For Every Printer";}, "paperworkSecondary", function(num) { if( $("#threeinone").length > 0 && num > 0) {$("#threeinone").remove();}flags.flag("threeinone", 900); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("threeinone", 0);});
	addPowerUp("lycos", {effort: 5120000, paperwork: 1120000, yessir: 0, bribery: 0}, "Lycos", function() { return "+1234 Paperwork For Every Email Address";}, "paperworkSecondary", function(num) { if( $("#lycos").length > 0 && num > 0) {$("#lycos").remove();}flags.flag("lycos", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("lycos", 0);});
	addPowerUp("compuserve", {effort: 42420000, paperwork: 9876543, yessir: 0, bribery: 0}, "CompuServe", function() { return "+5000 Paperwork For Every Email Address";}, "paperworkSecondary", function(num) { if( $("#compuserve").length > 0 && num > 0) {$("#compuserve").remove();}flags.flag("compuserve", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("compuserve", 0);});
	addPowerUp("gruel", {effort: 16140000, paperwork: 4810000, yessir: 721000, bribery: 0}, "Bowls Of Gruel", function() { return "+25000 Paperwork For Every Flock of orphans with your handwriting";}, "paperworkSecondary", function(num) { if( $("#gruel").length > 0 && num > 0) {$("#gruel").remove();}flags.flag("gruel", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("gruel", 0);});
	addPowerUp("posters", {effort: 616100000, paperwork: 10240000, yessir: 3210000, bribery: 0}, "Motivational Posters!", function() { return "+50000 Paperwork For Every Flock of orphans with your handwriting";}, "paperworkSecondary", function(num) { if( $("#posters").length > 0 && num > 0) {$("#posters").remove();}flags.flag("posters", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("posters", 0);});
	addPowerUp("laserguns", {effort: 397110000, paperwork: 21345589, yessir: 679000, bribery: 0}, "Laser Guns", function() { return "+150000 Paperwork For Every Robots. God damned robots.";}, "paperworkSecondary", function(num) { if( $("#laserguns").length > 0 && num > 0) {$("#laserguns").remove();}flags.flag("laserguns", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("laserguns", 0);});
	addPowerUp("sentience", {effort: 1337000000, paperwork: 144233377, yessir: 4110000, bribery: 0}, "Sentience", function() { return "+300000 Paperwork For Every Robots. God damned robots.";}, "paperworkSecondary", function(num) { if( $("#sentience").length > 0 && num > 0) {$("#sentience").remove();}flags.flag("sentience", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("sentience", 0);});
	addPowerUp("matrix", {effort: 794220000, paperwork: 64036767, yessir: 2716000, bribery: 0}, "Matrix of...Eh.", function() { return "+1750000 Paperwork For Every Living planet with amazing handwriting";}, "paperworkSecondary", function(num) { if( $("#matrix").length > 0 && num > 0) {$("#matrix").remove();}flags.flag("matrix", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("matrix", 0);});
	addPowerUp("disc", {effort: 1588440000, paperwork: 177407054, yessir: 5432000, bribery: 0}, "Silver Disc", function() { return "+5000000 Paperwork For Every Living planet with amazing handwriting";}, "paperworkSecondary", function(num) { if( $("#disc").length > 0 && num > 0) {$("#disc").remove();}flags.flag("disc", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("disc", 0);});
	addPowerUp("tyler", {effort: 0, paperwork: 0, yessir: 500, bribery: 0}, "John Tyler", function() { return "+2 Yes Sir For Every \"Tippecanoe and Tyler Too!\"";}, "yessirSecondary", function(num) { if( $("#tyler").length > 0 && num > 0) {$("#tyler").remove();}flags.flag("tyler", 2); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("tyler", 0);});
	addPowerUp("harrison", {effort: 0, paperwork: 0, yessir: 45000, bribery: 0}, "William Henry Harrison", function() { return "+50 Yes Sir For Every \"Tippecanoe and Tyler Too!\"";}, "yessirSecondary", function(num) { if( $("#harrison").length > 0 && num > 0) {$("#harrison").remove();}flags.flag("harrison", 50); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("harrison", 0);});
	addPowerUp("barkley", {effort: 0, paperwork: 0, yessir: 7600, bribery: 0}, "Alben W. Barkley", function() { return "+5 Yes Sir For Every \"Give 'Em Hell, Harry!\"";}, "yessirSecondary", function(num) { if( $("#barkley").length > 0 && num > 0) {$("#barkley").remove();}flags.flag("barkley", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("barkley", 0);});
	addPowerUp("truman", {effort: 0, paperwork: 0, yessir: 98000, bribery: 0}, "Harry S. Truman", function() { return "+70 Yes Sir For Every \"Give 'Em Hell, Harry!\"";}, "yessirSecondary", function(num) { if( $("#truman").length > 0 && num > 0) {$("#truman").remove();}flags.flag("truman", 70); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("truman", 0);});
	addPowerUp("nixon", {effort: 0, paperwork: 0, yessir: 50000, bribery: 0}, "Richard Nixon", function() { return "+10 Yes Sir For Every \"I Like Ike!\"";}, "yessirSecondary", function(num) { if( $("#nixon").length > 0 && num > 0) {$("#nixon").remove();}flags.flag("nixon", 10); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("nixon", 0);});
	addPowerUp("eisenhower", {effort: 0, paperwork: 0, yessir: 222000, bribery: 0}, "Dwight D. Eisenhower", function() { return "+115 Yes Sir For Every \"I Like Ike!\"";}, "yessirSecondary", function(num) { if( $("#eisenhower").length > 0 && num > 0) {$("#eisenhower").remove();}flags.flag("eisenhower", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("eisenhower", 0);});
	addPowerUp("johnson", {effort: 0, paperwork: 0, yessir: 920000, bribery: 0}, "Lyndon B. Johnson", function() { return "+115 Yes Sir For Every \"A Time For Greatness\"";}, "yessirSecondary", function(num) { if( $("#johnson").length > 0 && num > 0) {$("#johnson").remove();}flags.flag("johnson", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("johnson", 0);});
	addPowerUp("kennedy", {effort: 0, paperwork: 0, yessir: 3200000, bribery: 0}, "John F. Kennedy", function() { return "+420 Yes Sir For Every \"A Time For Greatness\"";}, "yessirSecondary", function(num) { if( $("#kennedy").length > 0 && num > 0) {$("#kennedy").remove();}flags.flag("kennedy", 420); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("kennedy", 0);});
	addPowerUp("quayle", {effort: 18660000, paperwork: 18660000, yessir: 18660000, bribery: 0}, "Dan Quayle", function() { return "+500 Yes Sir For Every \"No New Taxes\"";}, "yessirSecondary", function(num) { if( $("#quayle").length > 0 && num > 0) {$("#quayle").remove();}flags.flag("quayle", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("quayle", 0);});
	addPowerUp("bush", {effort: 49440000, paperwork: 49440000, yessir: 49440000, bribery: 0}, "George H. W. Bush", function() { return "+900 Yes Sir For Every \"No New Taxes\"";}, "yessirSecondary", function(num) { if( $("#bush").length > 0 && num > 0) {$("#bush").remove();}flags.flag("bush", 900); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("bush", 0);});
	addPowerUp("gore", {effort: 30720000, paperwork: 30720000, yessir: 30720000, bribery: 0}, "Al Gore", function() { return "+1234 Yes Sir For Every \"It's Time To Change America\"";}, "yessirSecondary", function(num) { if( $("#gore").length > 0 && num > 0) {$("#gore").remove();}flags.flag("gore", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("gore", 0);});
	addPowerUp("clinton", {effort: 254520000, paperwork: 254520000, yessir: 254520000, bribery: 0}, "Bill Clinton", function() { return "+5000 Yes Sir For Every \"It's Time To Change America\"";}, "yessirSecondary", function(num) { if( $("#clinton").length > 0 && num > 0) {$("#clinton").remove();}flags.flag("clinton", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("clinton", 0);});
	addPowerUp("biden", {effort: 96840000, paperwork: 96840000, yessir: 96840000, bribery: 0}, "Joe Biden", function() { return "+25000 Yes Sir For Every \"Change\"";}, "yessirSecondary", function(num) { if( $("#biden").length > 0 && num > 0) {$("#biden").remove();}flags.flag("biden", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("biden", 0);});
	addPowerUp("obama", {effort: 3696600000, paperwork: 3696600000, yessir: 3696600000, bribery: 0}, "Barack Obama", function() { return "+50000 Yes Sir For Every \"Change\"";}, "yessirSecondary", function(num) { if( $("#obama").length > 0 && num > 0) {$("#obama").remove();}flags.flag("obama", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("obama", 0);});
	addPowerUp("morelube", {effort: 2382660000, paperwork: 2382660000, yessir: 2382660000, bribery: 0}, "More Lube", function() { return "+150000 Yes Sir For Every \"Free Sexual Favors For Everyone!\"";}, "yessirSecondary", function(num) { if( $("#morelube").length > 0 && num > 0) {$("#morelube").remove();}flags.flag("morelube", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("morelube", 0);});
	addPowerUp("chickenmeanscock", {effort: 8022000000, paperwork: 8022000000, yessir: 8022000000, bribery: 0}, "A \"Chicken\" In Every \"Pot\"", function() { return "+300000 Yes Sir For Every \"Free Sexual Favors For Everyone!\"";}, "yessirSecondary", function(num) { if( $("#chickenmeanscock").length > 0 && num > 0) {$("#chickenmeanscock").remove();}flags.flag("chickenmeanscock", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("chickenmeanscock", 0);});
	addPowerUp("jobs", {effort: 4765320000, paperwork: 4765320000, yessir: 4765320000, bribery: 0}, "\"Jobs For Everyone, For Real!\"", function() { return "+1750000 Yes Sir For Every \"Here, Have Some Empty Promises\"";}, "yessirSecondary", function(num) { if( $("#jobs").length > 0 && num > 0) {$("#jobs").remove();}flags.flag("jobs", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("jobs", 0);});
	addPowerUp("hungryhungry", {effort: 9530640000, paperwork: 9530640000, yessir: 9530640000, bribery: 0}, "\"I Will End World Hunger Forever.\"", function() { return "+5000000 Yes Sir For Every \"Here, Have Some Empty Promises\"";}, "yessirSecondary", function(num) { if( $("#hungryhungry").length > 0 && num > 0) {$("#hungryhungry").remove();}flags.flag("hungryhungry", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("hungryhungry", 0);});
	addPowerUp("smallermoney", {effort: 350465354, paperwork: 17523268, yessir: 3504654, bribery: 500}, "Smaller Money", function() { return "+2 Bribery For Every Handful of Money";}, "briberySecondary", function(num) { if( $("#smallermoney").length > 0 && num > 0) {$("#smallermoney").remove();}flags.flag("smallermoney", 2); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("smallermoney", 0);});
	addPowerUp("biggerhands", {effort: 1086442597, paperwork: 54322131, yessir: 10864427, bribery: 45000}, "Bigger Hands", function() { return "+50 Bribery For Every Handful of Money";}, "briberySecondary", function(num) { if( $("#biggerhands").length > 0 && num > 0) {$("#biggerhands").remove();}flags.flag("biggerhands", 50); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("biggerhands", 0);});
	addPowerUp("wowenvelope", {effort: 655370211, paperwork: 32768510, yessir: 6553703, bribery: 7600}, "Envelope Made Of Money", function() { return "+5 Bribery For Every Envelope of Money";}, "briberySecondary", function(num) { if( $("#wowenvelope").length > 0 && num > 0) {$("#wowenvelope").remove();}flags.flag("wowenvelope", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("wowenvelope", 0);});
	addPowerUp("digitalenvelope", {effort: 2031647654, paperwork: 169701562, yessir: 33940315, bribery: 98000}, "Digital Envelopes", function() { return "+70 Bribery For Every Envelope of Money";}, "briberySecondary", function(num) { if( $("#digitalenvelope").length > 0 && num > 0) {$("#digitalenvelope").remove();}flags.flag("digitalenvelope", 70); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("digitalenvelope", 0);});
	addPowerUp("conch", {effort: 1402492252, paperwork: 466679295, yessir: 93335866, bribery: 50000}, "Conch", function() { return "+10 Bribery For Every Handbag of Money";}, "briberySecondary", function(num) { if( $("#conch").length > 0 && num > 0) {$("#conch").remove();}flags.flag("conch", 10); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("conch", 0);});
	addPowerUp("pradu", {effort: 4347725981, paperwork: 662684600, yessir: 132536930, bribery: 222000}, "Pradu", function() { return "+115 Bribery For Every Handbag of Money";}, "briberySecondary", function(num) { if( $("#pradu").length > 0 && num > 0) {$("#pradu").remove();}flags.flag("pradu", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("pradu", 0);});
	addPowerUp("inceptionpallet", {effort: 3394031251, paperwork: 941012131, yessir: 188202441, bribery: 920000}, "Pallets Are Made of Money", function() { return "+115 Bribery For Every Pallet of Money";}, "briberySecondary", function(num) { if( $("#inceptionpallet").length > 0 && num > 0) {$("#inceptionpallet").remove();}flags.flag("inceptionpallet", 115); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("inceptionpallet", 0);});
	addPowerUp("forklifts", {effort: 10521496878, paperwork: 1336237227, yessir: 267247466, bribery: 3200000}, "Forklifts, Also of Money", function() { return "+420 Bribery For Every Pallet of Money";}, "briberySecondary", function(num) { if( $("#forklifts").length > 0 && num > 0) {$("#forklifts").remove();}flags.flag("forklifts", 420); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("forklifts", 0);});
	addPowerUp("twobuildings", {effort: 9333585940, paperwork: 1897456862, yessir: 379491402, bribery: 18660000}, "Double Stacked Buildings", function() { return "+500 Bribery For Every Building of Money";}, "briberySecondary", function(num) { if( $("#twobuildings").length > 0 && num > 0) {$("#twobuildings").remove();}flags.flag("twobuildings", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("twobuildings", 0);});
	addPowerUp("twomansions", {effort: 28934116414, paperwork: 5882116272, yessir: 1176423346, bribery: 49440000}, "Double Stacked Mansions", function() { return "+900 Bribery For Every Building of Money";}, "briberySecondary", function(num) { if( $("#twomansions").length > 0 && num > 0) {$("#twomansions").remove();}flags.flag("twomansions", 900); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("twomansions", 0);});
	addPowerUp("community", {effort: 13253692034, paperwork: 662684600, yessir: 132536930, bribery: 30720000}, "Community Outreach (of Money)", function() { return "+1234 Bribery For Every City of Money";}, "briberySecondary", function(num) { if( $("#community").length > 0 && num > 0) {$("#community").remove();}flags.flag("community", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("community", 0);});
	addPowerUp("subway", {effort: 41086445305, paperwork: 2054322260, yessir: 410864483, bribery: 254520000}, "Subways filled with gold", function() { return "+5000 Bribery For Every City of Money";}, "briberySecondary", function(num) { if( $("#subway").length > 0 && num > 0) {$("#subway").remove();}flags.flag("subway", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("subway", 0);});
	addPowerUp("unofmoney", {effort: 18820242689, paperwork: 941012131, yessir: 188202441, bribery: 96840000}, "United Nations (of Money)", function() { return "+25000 Bribery For Every Nation of Money";}, "briberySecondary", function(num) { if( $("#unofmoney").length > 0 && num > 0) {$("#unofmoney").remove();}flags.flag("unofmoney", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("unofmoney", 0);});
	addPowerUp("continents", {effort: 58342752336, paperwork: 2917137606, yessir: 583427567, bribery: 3696600000}, "Continents of Money", function() { return "+50000 Bribery For Every Nation of Money";}, "briberySecondary", function(num) { if( $("#continents").length > 0 && num > 0) {$("#continents").remove();}flags.flag("continents", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("continents", 0);});
	addPowerUp("moon", {effort: 26724744618, paperwork: 1336237227, yessir: 267247466, bribery: 2382660000}, "Moons Made of Cheese! (and Money)", function() { return "+150000 Bribery For Every Planet of Money";}, "briberySecondary", function(num) { if( $("#moon").length > 0 && num > 0) {$("#moon").remove();}flags.flag("moon", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("moon", 0);});
	addPowerUp("uranus", {effort: 82846708316, paperwork: 4142335404, yessir: 828467145, bribery: 8022000000}, "Uranus Is Full Of Money", function() { return "+300000 Bribery For Every Planet of Money";}, "briberySecondary", function(num) { if( $("#uranus").length > 0 && num > 0) {$("#uranus").remove();}flags.flag("uranus", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("uranus", 0);});
	addPowerUp("diamond", {effort: 37949137358, paperwork: 1897456862, yessir: 379491402, bribery: 4765320000}, "Diamonds the Size of the Sun", function() { return "+1750000 Bribery For Every Solar System of Money";}, "briberySecondary", function(num) { if( $("#diamond").length > 0 && num > 0) {$("#diamond").remove();}flags.flag("diamond", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("diamond", 0);});
	addPowerUp("toomuchmoney", {effort: 117642325810, paperwork: 5882116272, yessir: 1176423346, bribery: 9530640000}, "WAY Too Much Money", function() { return "+5000000 Bribery For Every Solar System of Money";}, "briberySecondary", function(num) { if( $("#toomuchmoney").length > 0 && num > 0) {$("#toomuchmoney").remove();}flags.flag("toomuchmoney", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("toomuchmoney", 0);});
	addPowerUp("grindstone", {effort: 1100, paperwork: 0, yessir: 0, bribery: 0}, "Nose To The Grindstone", function() {return "+5 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#grindstone").length > 0 && num > 0) {$("#grindstone").remove();} flags.flag("grindstone", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("grindstone", 0);});
	addPowerUp("back", {effort: 21000, paperwork: 0, yessir: 0, bribery: 0}, "Put Your Back Into It", function() {return "+75 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#back").length > 0 && num > 0) {$("#back").remove();} flags.flag("back", 75); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("back", 0);});
	addPowerUp("pain", {effort: 480000, paperwork: 0, yessir: 0, bribery: 0}, "No Pain, No Gain", function() {return "+500 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#pain").length > 0 && num > 0) {$("#pain").remove();} flags.flag("pain", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("pain", 0);});
	addPowerUp("mile", {effort: 3456000, paperwork: 0, yessir: 0, bribery: 0}, "Go The Extra Mile", function() {return "+2500 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#mile").length > 0 && num > 0) {$("#mile").remove();} flags.flag("mile", 2500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("mile", 0);});
	addPowerUp("believe", {effort: 9999990, paperwork: 0, yessir: 0, bribery: 0}, "Believe In Yourself", function() {return "+30000 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#believe").length > 0 && num > 0) {$("#believe").remove();} flags.flag("believe", 30000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("believe", 0);});
	addPowerUp("advpaper", {effort: 0, paperwork: 1100, yessir: 0, bribery: 0}, "Advanced Paper", function() {return "+5 Paperwork For Every Wiggle";}, "paperworkTertiary", function(num) { if( $("#advpaper").length > 0 && num > 0) {$("#advpaper").remove();} flags.flag("advpaper", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("advpaper", 0);});
	addPowerUp("ultpaper", {effort: 0, paperwork: 21000, yessir: 0, bribery: 0}, "Ultimate Paper", function() {return "+75 Paperwork For Every Wiggle";}, "paperworkTertiary", function(num) { if( $("#ultpaper").length > 0 && num > 0) {$("#ultpaper").remove();} flags.flag("ultpaper", 75); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("ultpaper", 0);});
	addPowerUp("sweetpaper", {effort: 0, paperwork: 480000, yessir: 0, bribery: 0}, "Man, This Paper Is Sweet", function() {return "+500 Paperwork For Every Wiggle";}, "paperworkTertiary", function(num) { if( $("#sweetpaper").length > 0 && num > 0) {$("#sweetpaper").remove();} flags.flag("sweetpaper", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("sweetpaper", 0);});
	addPowerUp("multidimenpaper", {effort: 0, paperwork: 3456000, yessir: 0, bribery: 0}, "Multidimensional Paper", function() {return "+2500 Paperwork For Every Wiggle";}, "paperworkTertiary", function(num) { if( $("#multidimenpaper").length > 0 && num > 0) {$("#multidimenpaper").remove();} flags.flag("multidimenpaper", 2500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("multidimenpaper", 0);});
	addPowerUp("prettyprettypen", {effort: 0, paperwork: 9999990, yessir: 0, bribery: 0}, "A Really Pretty Pen", function() {return "+30000 Paperwork For Every Wiggle";}, "paperworkTertiary", function(num) { if( $("#prettyprettypen").length > 0 && num > 0) {$("#prettyprettypen").remove();} flags.flag("prettyprettypen", 30000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("prettyprettypen", 0);});
	addPowerUp("stronghandshakes", {effort: 0, paperwork: 0, yessir: 1100, bribery: 0}, "Stronger Handshakes", function() {return "+5 Yes Sir For Every Scroll";}, "yessirTertiary", function(num) { if( $("#stronghandshakes").length > 0 && num > 0) {$("#stronghandshakes").remove();} flags.flag("stronghandshakes", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("stronghandshakes", 0);});
	addPowerUp("deeperlies", {effort: 0, paperwork: 0, yessir: 21000, bribery: 0}, "Deeper Lies", function() {return "+75 Yes Sir For Every Scroll";}, "yessirTertiary", function(num) { if( $("#deeperlies").length > 0 && num > 0) {$("#deeperlies").remove();} flags.flag("deeperlies", 75); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("deeperlies", 0);});
	addPowerUp("longcommercials", {effort: 0, paperwork: 0, yessir: 480000, bribery: 0}, "Longer Commercials", function() {return "+500 Yes Sir For Every Scroll";}, "yessirTertiary", function(num) { if( $("#longcommercials").length > 0 && num > 0) {$("#longcommercials").remove();} flags.flag("longcommercials", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("longcommercials", 0);});
	addPowerUp("infiltratereddit", {effort: 0, paperwork: 0, yessir: 3456000, bribery: 0}, "Infiltrate Reddit", function() {return "+2500 Yes Sir For Every Scroll";}, "yessirTertiary", function(num) { if( $("#infiltratereddit").length > 0 && num > 0) {$("#infiltratereddit").remove();} flags.flag("infiltratereddit", 2500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("infiltratereddit", 0);});
	addPowerUp("telepathy", {effort: 0, paperwork: 0, yessir: 9999990, bribery: 0}, "Telepathy", function() {return "+30000 Yes Sir For Every Scroll";}, "yessirTertiary", function(num) { if( $("#telepathy").length > 0 && num > 0) {$("#telepathy").remove();} flags.flag("telepathy", 30000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("telepathy", 0);});
	addPowerUp("fivebribe", {effort: 0, paperwork: 0, yessir: 0, bribery: 1100}, "$5 Per Bribe", function() {return "+5 Bribery For Every Drag";}, "briberyTertiary", function(num) { if( $("#fivebribe").length > 0 && num > 0) {$("#fivebribe").remove();} flags.flag("fivebribe", 5); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("fivebribe", 0);});
	addPowerUp("seventyfivebribe", {effort: 0, paperwork: 0, yessir: 0, bribery: 21000}, "$75 Per Bribe", function() {return "+75 Bribery For Every Drag";}, "briberyTertiary", function(num) { if( $("#seventyfivebribe").length > 0 && num > 0) {$("#seventyfivebribe").remove();} flags.flag("seventyfivebribe", 75); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("seventyfivebribe", 0);});
	addPowerUp("fivehundredbribe", {effort: 0, paperwork: 0, yessir: 0, bribery: 480000}, "$500 Per Bribe", function() {return "+500 Bribery For Every Drag";}, "briberyTertiary", function(num) { if( $("#fivehundredbribe").length > 0 && num > 0) {$("#fivehundredbribe").remove();} flags.flag("fivehundredbribe", 500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("fivehundredbribe", 0);});
	addPowerUp("twentyfivehundredbribe", {effort: 0, paperwork: 0, yessir: 0, bribery: 3456000}, "$2,500 Per Bribe", function() {return "+2500 Bribery For Every Drag";}, "briberyTertiary", function(num) { if( $("#twentyfivehundredbribe").length > 0 && num > 0) {$("#twentyfivehundredbribe").remove();} flags.flag("twentyfivehundredbribe", 2500); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("twentyfivehundredbribe", 0);});
	addPowerUp("thirtythousandbribe", {effort: 0, paperwork: 0, yessir: 0, bribery: 9999990}, "$30,000 Per Bribe", function() {return "+30000 Bribery For Every Drag";}, "briberyTertiary", function(num) { if( $("#thirtythousandbribe").length > 0 && num > 0) {$("#thirtythousandbribe").remove();} flags.flag("thirtythousandbribe", 30000); return {"effort": 0,"paperwork": 0,"yessir": 0, "bribery": 0};}, true, function() { flags.flag("thirtythousandbribe", 0);});
/*
	addPowerUp("stranger", {effort: 15, paperwork: 0, yessir: 0}, "Stranger", function() { return "+" + (0.1 + flags.flag("perfectstrangers") + flags.flag("perfectstrangers2")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (0.1 + flags.flag("perfectstrangers") + flags.flag("perfectstrangers2")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("acquaintance", {effort: 100, paperwork: 0, yessir: 0}, "Acquaintance", function() { return "+" + (0.5 + flags.flag("gettingtoknowyou") + flags.flag("gettingtoknowallaboutyou")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (0.5 + flags.flag("gettingtoknowyou") + flags.flag("gettingtoknowallaboutyou")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("friend", {effort: 900, paperwork: 0, yessir: 0}, "Friend", function() { return "+" + (3 + flags.flag("joey") + flags.flag("chandler")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (3 + flags.flag("joey") + flags.flag("chandler")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("bro", {effort: 25437, paperwork: 0, yessir: 0}, "Bro", function() { return "+" + (50 + flags.flag("budlight") + flags.flag("collar")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (50 + flags.flag("budlight") + flags.flag("collar")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("bestfriend", {effort: 150000, paperwork: 5000, yessir: 0}, "Best Friend", function() { return "+" + (300 + flags.flag("pizza") + flags.flag("hideabody")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (300 + flags.flag("pizza") + flags.flag("hideabody")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("bff", {effort: 314159, paperwork: 133700, yessir: 0}, "BFF", function() { return "+" + (2400 + flags.flag("idkmbffj") + flags.flag("instantgram")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (2400 + flags.flag("idkmbffj") + flags.flag("instantgram")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("personallawyer", {effort: 1000000, paperwork: 675000, yessir: 10000}, "Personal Lawyer", function() { return "+" + (9999 + flags.flag("objection") + flags.flag("takethat")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (9999 + flags.flag("objection") + flags.flag("takethat")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("sigother", {effort: 11235813, paperwork: 3333360, yessir: 270000}, "Significant Other", function() { return "+" + (70000 + flags.flag("cohabitate") + flags.flag("cosign")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (70000 + flags.flag("cohabitate") + flags.flag("cosign")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("superpac", {effort: 81000000, paperwork: 7598950, yessir: 999000}, "Super PAC", function() { return "+" + (500000 + flags.flag("babypac") + flags.flag("mspac")) + " Effort Per Second";}, "effortPrimary", function(num) {return {"effort": (500000 + flags.flag("babypac") + flags.flag("mspac")) * num,"paperwork": 0,"yessir": 0};}, false);
	addPowerUp("staples", {effort: 0, paperwork: 15, yessir: 0}, "Staples", function() { return "+" + (0.1 + flags.flag("paperclips") + flags.flag("paperbinders")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (0.1 + flags.flag("paperclips") + flags.flag("paperbinders")) * num,"yessir": 0};}, false)
	addPowerUp("pencil", {effort: 0, paperwork: 100, yessir: 0}, "Pencil", function() { return "+" + (0.5 + flags.flag("sharpenedPencil") + flags.flag("mechanicalpencil")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (0.5 + flags.flag("sharpenedPencil") + flags.flag("mechanicalpencil")) * num,"yessir": 0};}, false)
	addPowerUp("pen", {effort: 0, paperwork: 900, yessir: 0}, "Pen", function() { return "+" + (3 + flags.flag("moreink") + flags.flag("cyberpen")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (3 + flags.flag("moreink") + flags.flag("cyberpen")) * num,"yessir": 0};}, false)
	addPowerUp("typewriter", {effort: 0, paperwork: 25437, yessir: 0}, "Typewriter", function() { return "+" + (50 + flags.flag("wordprocessor") + flags.flag("talktotext")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (50 + flags.flag("wordprocessor") + flags.flag("talktotext")) * num,"yessir": 0};}, false)
	addPowerUp("printer", {effort: 540000, paperwork: 150000, yessir: 0}, "Printer", function() { return "+" + (300 + flags.flag("laserprinter") + flags.flag("threeinone")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (300 + flags.flag("laserprinter") + flags.flag("threeinone")) * num,"yessir": 0};}, false)
	addPowerUp("altavista", {effort: 4850000, paperwork: 314159, yessir: 0}, "Email Address", function() { return "+" + (2400 + flags.flag("lycos") + flags.flag("compuserve")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (2400 + flags.flag("lycos") + flags.flag("compuserve")) * num,"yessir": 0};}, false)
	addPowerUp("orphans", {effort: 25600000, paperwork: 1000000, yessir: 80000}, "Flock of orphans with your handwriting", function() { return "+" + (9999 + flags.flag("gruel") + flags.flag("posters")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (9999 + flags.flag("gruel") + flags.flag("posters")) * num,"yessir": 0};}, false)
	addPowerUp("robots", {effort: 101200000, paperwork: 11235813, yessir: 670000}, "Robots. God damned robots.", function() { return "+" + (70000 + flags.flag("laserguns") + flags.flag("sentience")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (70000 + flags.flag("laserguns") + flags.flag("sentience")) * num,"yessir": 0};}, false)
	addPowerUp("unicron", {effort: 155848000, paperwork: 81000000, yessir: 1599000}, "Living planet with amazing handwriting", function() { return "+" + (500000 + flags.flag("matrix") + flags.flag("disc")) + " Paperwork Per Second";}, "paperworkPrimary", function(num) {return {"effort": 0,"paperwork": (500000 + flags.flag("matrix") + flags.flag("disc")) * num,"yessir": 0};}, false)
	addPowerUp("tippiecanoe", {effort: 0, paperwork: 0, yessir: 15}, "\"Tippecanoe and Tyler Too!\"", function() { return "+" + (0.1 + flags.flag("tyler") + flags.flag("harrison")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (0.1 + flags.flag("tyler") + flags.flag("harrison")) * num};}, false)
	addPowerUp("harry", {effort: 0, paperwork: 0, yessir: 100}, "\"Give 'Em Hell, Harry!\"", function() { return "+" + (0.5 + flags.flag("barkley") + flags.flag("truman")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (0.5 + flags.flag("barkley") + flags.flag("truman")) * num};}, false)
	addPowerUp("ike", {effort: 0, paperwork: 0, yessir: 900}, "\"I Like Ike!\"", function() { return "+" + (3 + flags.flag("nixon") + flags.flag("eisenhower")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (3 + flags.flag("nixon") + flags.flag("eisenhower")) * num};}, false)
	addPowerUp("great", {effort: 0, paperwork: 0, yessir: 25437}, "\"A Time For Greatness\"", function() { return "+" + (50 + flags.flag("johnson") + flags.flag("kennedy")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (50 + flags.flag("johnson") + flags.flag("kennedy")) * num};}, false)
	addPowerUp("taxes", {effort: 9110000, paperwork: 647000, yessir: 150000}, "\"No New Taxes\"", function() { return "+" + (300 + flags.flag("quayle") + flags.flag("bush")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (300 + flags.flag("quayle") + flags.flag("bush")) * num};}, false)
	addPowerUp("timeforchange", {effort: 44400000, paperwork: 1234567, yessir: 314159}, "\"It's Time To Change America\"", function() { return "+" + (2400 + flags.flag("gore") + flags.flag("clinton")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (2400 + flags.flag("gore") + flags.flag("clinton")) * num};}, false)
	addPowerUp("change", {effort: 322222222, paperwork: 12345678, yessir: 1000000}, "\"Change\"", function() { return "+" + (9999 + flags.flag("biden") + flags.flag("obama")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (9999 + flags.flag("biden") + flags.flag("obama")) * num};}, false)
	addPowerUp("handsacrossamerica", {effort: 5000000000, paperwork: 123456789, yessir: 11235813}, "\"Free Sexual Favors For Everyone!\"", function() { return "+" + (70000 + flags.flag("morelube") + flags.flag("chickenmeanscock")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (70000 + flags.flag("morelube") + flags.flag("chickenmeanscock")) * num};}, false)
	addPowerUp("morelies", {effort: 8500000000, paperwork: 370370367, yessir: 134829756}, "\"Here, Have Some Empty Promises\"", function() { return "+" + (500000 + flags.flag("jobs") + flags.flag("hungryhungry")) + " Yes Sir Per Second";}, "yessirPrimary", function(num) {return {"effort": 0,"paperwork": 0,"yessir": (500000 + flags.flag("jobs") + flags.flag("hungryhungry")) * num};}, false)
	addPowerUp("perfectstrangers", {effort: 500, paperwork: 0, yessir: 0}, "Perfect Strangers", function() { return "+2 Effort For Every Stranger";}, "effortSecondary", function(num) { if( $("#perfectstrangers").length > 0 && num > 0) {$("#perfectstrangers").remove();}flags.flag("perfectstrangers", 2); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("perfectstrangers", 0);});
	addPowerUp("perfectstrangers2", {effort: 45000, paperwork: 0, yessir: 0}, "Perfect Strangers Mk. II", function() { return "+50 Effort For Every Stranger";}, "effortSecondary", function(num) { if( $("#perfectstrangers2").length > 0 && num > 0) {$("#perfectstrangers2").remove();}flags.flag("perfectstrangers2", 50); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("perfectstrangers2", 0);});
	addPowerUp("gettingtoknowyou", {effort: 7600, paperwork: 0, yessir: 0}, "Getting To Know You", function() { return "+5 Effort For Every Acquaintance";}, "effortSecondary", function(num) { if( $("#gettingtoknowyou").length > 0 && num > 0) {$("#gettingtoknowyou").remove();}flags.flag("gettingtoknowyou", 5); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("gettingtoknowyou", 0);});
	addPowerUp("gettingtoknowallaboutyou", {effort: 98000, paperwork: 0, yessir: 0}, "Getting To Know All About You", function() { return "+70 Effort For Every Acquaintance";}, "effortSecondary", function(num) { if( $("#gettingtoknowallaboutyou").length > 0 && num > 0) {$("#gettingtoknowallaboutyou").remove();}flags.flag("gettingtoknowallaboutyou", 70); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("gettingtoknowallaboutyou", 0);});
	addPowerUp("joey", {effort: 50000, paperwork: 0, yessir: 0}, "Joey", function() { return "+10 Effort For Every Friend";}, "effortSecondary", function(num) { if( $("#joey").length > 0 && num > 0) {$("#joey").remove();}flags.flag("joey", 10); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("joey", 0);});
	addPowerUp("chandler", {effort: 222000, paperwork: 0, yessir: 0}, "Chandler", function() { return "+115 Effort For Every Friend";}, "effortSecondary", function(num) { if( $("#chandler").length > 0 && num > 0) {$("#chandler").remove();}flags.flag("chandler", 115); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("chandler", 0);});
	addPowerUp("budlight", {effort: 920000, paperwork: 0, yessir: 0}, "Bud Light", function() { return "+115 Effort For Every Bro";}, "effortSecondary", function(num) { if( $("#budlight").length > 0 && num > 0) {$("#budlight").remove();}flags.flag("budlight", 115); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("budlight", 0);});
	addPowerUp("collar", {effort: 3200000, paperwork: 0, yessir: 0}, "Popped Collar", function() { return "+420 Effort For Every Bro";}, "effortSecondary", function(num) { if( $("#collar").length > 0 && num > 0) {$("#collar").remove();}flags.flag("collar", 420); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("collar", 0);});
	addPowerUp("pizza", {effort: 720000, paperwork: 42000, yessir: 0}, "Pizza", function() { return "+500 Effort For Every Best Friend";}, "effortSecondary", function(num) { if( $("#pizza").length > 0 && num > 0) {$("#pizza").remove();}flags.flag("pizza", 500); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("pizza", 0);});
	addPowerUp("hideabody", {effort: 3200000, paperwork: 118000, yessir: 0}, "Hide A Body Maybe?", function() { return "+900 Effort For Every Best Friend";}, "effortSecondary", function(num) { if( $("#hideabody").length > 0 && num > 0) {$("#hideabody").remove();}flags.flag("hideabody", 900); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("hideabody", 0);});
	addPowerUp("idkmbffj", {effort: 1120000, paperwork: 77777, yessir: 0}, "IDK, my BFF Jill?", function() { return "+1234 Effort For Every BFF";}, "effortSecondary", function(num) { if( $("#idkmbffj").length > 0 && num > 0) {$("#idkmbffj").remove();}flags.flag("idkmbffj", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("idkmbffj", 0);});
	addPowerUp("instantgram", {effort: 9876543, paperwork: 300000, yessir: 0}, "Instant Gram (That's What The Kids Call It?)", function() { return "+5000 Effort For Every BFF";}, "effortSecondary", function(num) { if( $("#instantgram").length > 0 && num > 0) {$("#instantgram").remove();}flags.flag("instantgram", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("instantgram", 0);});
	addPowerUp("objection", {effort: 4810000, paperwork: 1475000, yessir: 49000}, "OBJECTION!", function() { return "+25000 Effort For Every Personal Lawyer";}, "effortSecondary", function(num) { if( $("#objection").length > 0 && num > 0) {$("#objection").remove();}flags.flag("objection", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("objection", 0);});
	addPowerUp("takethat", {effort: 10240000, paperwork: 6675000, yessir: 260000}, "TAKE THAT!!", function() { return "+50000 Effort For Every Personal Lawyer";}, "effortSecondary", function(num) { if( $("#takethat").length > 0 && num > 0) {$("#takethat").remove();}flags.flag("takethat", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("takethat", 0);});
	addPowerUp("cohabitate", {effort: 21345589, paperwork: 9999990, yessir: 679000}, "Move In Together", function() { return "+150000 Effort For Every Significant Other";}, "effortSecondary", function(num) { if( $("#cohabitate").length > 0 && num > 0) {$("#cohabitate").remove();}flags.flag("cohabitate", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("cohabitate", 0);});
	addPowerUp("cosign", {effort: 144233377, paperwork: 50000000, yessir: 4110000}, "Buy A House!", function() { return "+300000 Effort For Every Significant Other";}, "effortSecondary", function(num) { if( $("#cosign").length > 0 && num > 0) {$("#cosign").remove();}flags.flag("cosign", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("cosign", 0);});
	addPowerUp("babypac", {effort: 231777551, paperwork: 32000000, yessir: 1241100}, "Baby PAC", function() { return "+1750000 Effort For Every Super PAC";}, "effortSecondary", function(num) { if( $("#babypac").length > 0 && num > 0) {$("#babypac").remove();}flags.flag("babypac", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("babypac", 0);});
	addPowerUp("mspac", {effort: 1557773120, paperwork: 68800000, yessir: 9000000}, "Ms. PAC", function() { return "+5000000 Effort For Every Super PAC";}, "effortSecondary", function(num) { if( $("#mspac").length > 0 && num > 0) {$("#mspac").remove();}flags.flag("mspac", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("mspac", 0);});
	addPowerUp("paperclips", {effort: 0, paperwork: 500, yessir: 0}, "Paperclips", function() { return "+2 Paperwork For Every Staples";}, "paperworkSecondary", function(num) { if( $("#paperclips").length > 0 && num > 0) {$("#paperclips").remove();}flags.flag("paperclips", 2); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("paperclips", 0);});
	addPowerUp("paperbinders", {effort: 0, paperwork: 45000, yessir: 0}, "Paper Binders", function() { return "+50 Paperwork For Every Staples";}, "paperworkSecondary", function(num) { if( $("#paperbinders").length > 0 && num > 0) {$("#paperbinders").remove();}flags.flag("paperbinders", 50); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("paperbinders", 0);});
	addPowerUp("sharpenedPencil", {effort: 0, paperwork: 7600, yessir: 0}, "Sharpened Pencil", function() { return "+5 Paperwork For Every Pencil";}, "paperworkSecondary", function(num) { if( $("#sharpenedPencil").length > 0 && num > 0) {$("#sharpenedPencil").remove();}flags.flag("sharpenedPencil", 5); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("sharpenedPencil", 0);});
	addPowerUp("mechanicalpencil", {effort: 0, paperwork: 98000, yessir: 0}, "Mechanical Pencil", function() { return "+70 Paperwork For Every Pencil";}, "paperworkSecondary", function(num) { if( $("#mechanicalpencil").length > 0 && num > 0) {$("#mechanicalpencil").remove();}flags.flag("mechanicalpencil", 70); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("mechanicalpencil", 0);});
	addPowerUp("moreink", {effort: 0, paperwork: 50000, yessir: 0}, "MORE. INK.", function() { return "+10 Paperwork For Every Pen";}, "paperworkSecondary", function(num) { if( $("#moreink").length > 0 && num > 0) {$("#moreink").remove();}flags.flag("moreink", 10); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("moreink", 0);});
	addPowerUp("cyberpen", {effort: 0, paperwork: 222000, yessir: 0}, "Cybernetic Pen", function() { return "+115 Paperwork For Every Pen";}, "paperworkSecondary", function(num) { if( $("#cyberpen").length > 0 && num > 0) {$("#cyberpen").remove();}flags.flag("cyberpen", 115); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("cyberpen", 0);});
	addPowerUp("wordprocessor", {effort: 0, paperwork: 920000, yessir: 0}, "Word Processor", function() { return "+115 Paperwork For Every Typewriter";}, "paperworkSecondary", function(num) { if( $("#wordprocessor").length > 0 && num > 0) {$("#wordprocessor").remove();}flags.flag("wordprocessor", 115); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("wordprocessor", 0);});
	addPowerUp("talktotext", {effort: 0, paperwork: 3200000, yessir: 0}, "Talk To Text", function() { return "+420 Paperwork For Every Typewriter";}, "paperworkSecondary", function(num) { if( $("#talktotext").length > 0 && num > 0) {$("#talktotext").remove();}flags.flag("talktotext", 420); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("talktotext", 0);});
	addPowerUp("laserprinter", {effort: 3110000, paperwork: 720000, yessir: 0}, "Laser Printer", function() { return "+500 Paperwork For Every Printer";}, "paperworkSecondary", function(num) { if( $("#laserprinter").length > 0 && num > 0) {$("#laserprinter").remove();}flags.flag("laserprinter", 500); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("laserprinter", 0);});
	addPowerUp("threeinone", {effort: 8240000, paperwork: 3200000, yessir: 0}, "Three In One Printer", function() { return "+900 Paperwork For Every Printer";}, "paperworkSecondary", function(num) { if( $("#threeinone").length > 0 && num > 0) {$("#threeinone").remove();}flags.flag("threeinone", 900); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("threeinone", 0);});
	addPowerUp("lycos", {effort: 5120000, paperwork: 1120000, yessir: 0}, "Lycos", function() { return "+1234 Paperwork For Every Email Address";}, "paperworkSecondary", function(num) { if( $("#lycos").length > 0 && num > 0) {$("#lycos").remove();}flags.flag("lycos", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("lycos", 0);});
	addPowerUp("compuserve", {effort: 42420000, paperwork: 9876543, yessir: 0}, "CompuServe", function() { return "+5000 Paperwork For Every Email Address";}, "paperworkSecondary", function(num) { if( $("#compuserve").length > 0 && num > 0) {$("#compuserve").remove();}flags.flag("compuserve", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("compuserve", 0);});
	addPowerUp("gruel", {effort: 16140000, paperwork: 4810000, yessir: 721000}, "Bowls Of Gruel", function() { return "+25000 Paperwork For Every Flock of orphans with your handwriting";}, "paperworkSecondary", function(num) { if( $("#gruel").length > 0 && num > 0) {$("#gruel").remove();}flags.flag("gruel", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("gruel", 0);});
	addPowerUp("posters", {effort: 616100000, paperwork: 10240000, yessir: 3210000}, "Motivational Posters!", function() { return "+50000 Paperwork For Every Flock of orphans with your handwriting";}, "paperworkSecondary", function(num) { if( $("#posters").length > 0 && num > 0) {$("#posters").remove();}flags.flag("posters", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("posters", 0);});
	addPowerUp("laserguns", {effort: 397110000, paperwork: 21345589, yessir: 679000}, "Laser Guns", function() { return "+150000 Paperwork For Every Robots. God damned robots.";}, "paperworkSecondary", function(num) { if( $("#laserguns").length > 0 && num > 0) {$("#laserguns").remove();}flags.flag("laserguns", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("laserguns", 0);});
	addPowerUp("sentience", {effort: 1337000000, paperwork: 144233377, yessir: 4110000}, "Sentience", function() { return "+300000 Paperwork For Every Robots. God damned robots.";}, "paperworkSecondary", function(num) { if( $("#sentience").length > 0 && num > 0) {$("#sentience").remove();}flags.flag("sentience", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("sentience", 0);});
	addPowerUp("matrix", {effort: 794220000, paperwork: 64036767, yessir: 2716000}, "Matrix of...Eh.", function() { return "+1750000 Paperwork For Every Living planet with amazing handwriting";}, "paperworkSecondary", function(num) { if( $("#matrix").length > 0 && num > 0) {$("#matrix").remove();}flags.flag("matrix", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("matrix", 0);});
	addPowerUp("disc", {effort: 1588440000, paperwork: 177407054, yessir: 5432000}, "Silver Disc", function() { return "+5000000 Paperwork For Every Living planet with amazing handwriting";}, "paperworkSecondary", function(num) { if( $("#disc").length > 0 && num > 0) {$("#disc").remove();}flags.flag("disc", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("disc", 0);});
	addPowerUp("tyler", {effort: 0, paperwork: 0, yessir: 500}, "John Tyler", function() { return "+2 Yes Sir For Every \"Tippecanoe and Tyler Too!\"";}, "yessirSecondary", function(num) { if( $("#tyler").length > 0 && num > 0) {$("#tyler").remove();}flags.flag("tyler", 2); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("tyler", 0);});
	addPowerUp("harrison", {effort: 0, paperwork: 0, yessir: 45000}, "William Henry Harrison", function() { return "+50 Yes Sir For Every \"Tippecanoe and Tyler Too!\"";}, "yessirSecondary", function(num) { if( $("#harrison").length > 0 && num > 0) {$("#harrison").remove();}flags.flag("harrison", 50); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("harrison", 0);});
	addPowerUp("barkley", {effort: 0, paperwork: 0, yessir: 7600}, "Alben W. Barkley", function() { return "+5 Yes Sir For Every \"Give 'Em Hell, Harry!\"";}, "yessirSecondary", function(num) { if( $("#barkley").length > 0 && num > 0) {$("#barkley").remove();}flags.flag("barkley", 5); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("barkley", 0);});
	addPowerUp("truman", {effort: 0, paperwork: 0, yessir: 98000}, "Harry S. Truman", function() { return "+70 Yes Sir For Every \"Give 'Em Hell, Harry!\"";}, "yessirSecondary", function(num) { if( $("#truman").length > 0 && num > 0) {$("#truman").remove();}flags.flag("truman", 70); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("truman", 0);});
	addPowerUp("nixon", {effort: 0, paperwork: 0, yessir: 50000}, "Richard Nixon", function() { return "+10 Yes Sir For Every \"I Like Ike!\"";}, "yessirSecondary", function(num) { if( $("#nixon").length > 0 && num > 0) {$("#nixon").remove();}flags.flag("nixon", 10); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("nixon", 0);});
	addPowerUp("eisenhower", {effort: 0, paperwork: 0, yessir: 222000}, "Dwight D. Eisenhower", function() { return "+115 Yes Sir For Every \"I Like Ike!\"";}, "yessirSecondary", function(num) { if( $("#eisenhower").length > 0 && num > 0) {$("#eisenhower").remove();}flags.flag("eisenhower", 115); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("eisenhower", 0);});
	addPowerUp("johnson", {effort: 0, paperwork: 0, yessir: 920000}, "Lyndon B. Johnson", function() { return "+115 Yes Sir For Every \"A Time For Greatness\"";}, "yessirSecondary", function(num) { if( $("#johnson").length > 0 && num > 0) {$("#johnson").remove();}flags.flag("johnson", 115); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("johnson", 0);});
	addPowerUp("kennedy", {effort: 0, paperwork: 0, yessir: 3200000}, "John F. Kennedy", function() { return "+420 Yes Sir For Every \"A Time For Greatness\"";}, "yessirSecondary", function(num) { if( $("#kennedy").length > 0 && num > 0) {$("#kennedy").remove();}flags.flag("kennedy", 420); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("kennedy", 0);});
	addPowerUp("quayle", {effort: 18660000, paperwork: 18660000, yessir: 18660000}, "Dan Quayle", function() { return "+500 Yes Sir For Every \"No New Taxes\"";}, "yessirSecondary", function(num) { if( $("#quayle").length > 0 && num > 0) {$("#quayle").remove();}flags.flag("quayle", 500); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("quayle", 0);});
	addPowerUp("bush", {effort: 49440000, paperwork: 49440000, yessir: 49440000}, "George H. W. Bush", function() { return "+900 Yes Sir For Every \"No New Taxes\"";}, "yessirSecondary", function(num) { if( $("#bush").length > 0 && num > 0) {$("#bush").remove();}flags.flag("bush", 900); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("bush", 0);});
	addPowerUp("gore", {effort: 30720000, paperwork: 30720000, yessir: 30720000}, "Al Gore", function() { return "+1234 Yes Sir For Every \"It's Time To Change America\"";}, "yessirSecondary", function(num) { if( $("#gore").length > 0 && num > 0) {$("#gore").remove();}flags.flag("gore", 1234); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("gore", 0);});
	addPowerUp("clinton", {effort: 254520000, paperwork: 254520000, yessir: 254520000}, "Bill Clinton", function() { return "+5000 Yes Sir For Every \"It's Time To Change America\"";}, "yessirSecondary", function(num) { if( $("#clinton").length > 0 && num > 0) {$("#clinton").remove();}flags.flag("clinton", 5000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("clinton", 0);});
	addPowerUp("biden", {effort: 96840000, paperwork: 96840000, yessir: 96840000}, "Joe Biden", function() { return "+25000 Yes Sir For Every \"Change\"";}, "yessirSecondary", function(num) { if( $("#biden").length > 0 && num > 0) {$("#biden").remove();}flags.flag("biden", 25000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("biden", 0);});
	addPowerUp("obama", {effort: 3696600000, paperwork: 3696600000, yessir: 3696600000}, "Barack Obama", function() { return "+50000 Yes Sir For Every \"Change\"";}, "yessirSecondary", function(num) { if( $("#obama").length > 0 && num > 0) {$("#obama").remove();}flags.flag("obama", 50000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("obama", 0);});
	addPowerUp("morelube", {effort: 2382660000, paperwork: 2382660000, yessir: 2382660000}, "More Lube", function() { return "+150000 Yes Sir For Every \"Free Sexual Favors For Everyone!\"";}, "yessirSecondary", function(num) { if( $("#morelube").length > 0 && num > 0) {$("#morelube").remove();}flags.flag("morelube", 150000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("morelube", 0);});
	addPowerUp("chickenmeanscock", {effort: 8022000000, paperwork: 8022000000, yessir: 8022000000}, "A \"Chicken\" In Every \"Pot\"", function() { return "+300000 Yes Sir For Every \"Free Sexual Favors For Everyone!\"";}, "yessirSecondary", function(num) { if( $("#chickenmeanscock").length > 0 && num > 0) {$("#chickenmeanscock").remove();}flags.flag("chickenmeanscock", 300000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("chickenmeanscock", 0);});
	addPowerUp("jobs", {effort: 4765320000, paperwork: 4765320000, yessir: 4765320000}, "\"Jobs For Everyone, For Real!\"", function() { return "+1750000 Yes Sir For Every \"Here, Have Some Empty Promises\"";}, "yessirSecondary", function(num) { if( $("#jobs").length > 0 && num > 0) {$("#jobs").remove();}flags.flag("jobs", 1750000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("jobs", 0);});
	addPowerUp("hungryhungry", {effort: 9530640000, paperwork: 9530640000, yessir: 9530640000}, "\"I Will End World Hunger Forever.\"", function() { return "+5000000 Yes Sir For Every \"Here, Have Some Empty Promises\"";}, "yessirSecondary", function(num) { if( $("#hungryhungry").length > 0 && num > 0) {$("#hungryhungry").remove();}flags.flag("hungryhungry", 5000000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("hungryhungry", 0);});
	addPowerUp("grindstone", {effort: 1100, paperwork: 0, yessir: 0}, "Nose To The Grindstone", function() {return "+5 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#grindstone").length > 0 && num > 0) {$("#grindstone").remove();} flags.flag("grindstone", 5); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("grindstone", 0);});
	addPowerUp("back", {effort: 21000, paperwork: 0, yessir: 0}, "Put Your Back Into It", function() {return "+75 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#back").length > 0 && num > 0) {$("#back").remove();} flags.flag("back", 75); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("back", 0);});
	addPowerUp("pain", {effort: 480000, paperwork: 0, yessir: 0}, "No Pain, No Gain", function() {return "+500 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#pain").length > 0 && num > 0) {$("#pain").remove();} flags.flag("pain", 500); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("pain", 0);});
	addPowerUp("mile", {effort: 3456000, paperwork: 0, yessir: 0}, "Go The Extra Mile", function() {return "+2500 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#mile").length > 0 && num > 0) {$("#mile").remove();} flags.flag("mile", 2500); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("mile", 0);});
	addPowerUp("believe", {effort: 9999990, paperwork: 0, yessir: 0}, "Believe In Yourself", function() {return "+30000 Effort For Every Click";}, "effortTertiary", function(num) { if( $("#believe").length > 0 && num > 0) {$("#believe").remove();} flags.flag("believe", 30000); return {"effort": 0,"paperwork": 0,"yessir": 0};}, true, function() { flags.flag("believe", 0);});
*/
}